//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxtService.Proxy.FxtCollateral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataCollateral", Namespace="http://schemas.datacontract.org/2004/07/FxtNHibernate.FxtDataDomain.Entities")]
    [System.SerializableAttribute()]
    public partial class DataCollateral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlankIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchCityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BuildingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BuildingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClerkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FirstPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstallmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LineOfcreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LoanAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanCardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanCardinalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanCensusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LoanDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanEducationalBackgroundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanInterestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanMarriageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanPeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LoanSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MonthsPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurposeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoadNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubAreaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agency {
            get {
                return this.AgencyField;
            }
            set {
                if ((object.ReferenceEquals(this.AgencyField, value) != true)) {
                    this.AgencyField = value;
                    this.RaisePropertyChanged("Agency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaId {
            get {
                return this.AreaIdField;
            }
            set {
                if ((this.AreaIdField.Equals(value) != true)) {
                    this.AreaIdField = value;
                    this.RaisePropertyChanged("AreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlankId {
            get {
                return this.BlankIdField;
            }
            set {
                if ((this.BlankIdField.Equals(value) != true)) {
                    this.BlankIdField = value;
                    this.RaisePropertyChanged("BlankId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchCityId {
            get {
                return this.BranchCityIdField;
            }
            set {
                if ((this.BranchCityIdField.Equals(value) != true)) {
                    this.BranchCityIdField = value;
                    this.RaisePropertyChanged("BranchCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BuildingArea {
            get {
                return this.BuildingAreaField;
            }
            set {
                if ((this.BuildingAreaField.Equals(value) != true)) {
                    this.BuildingAreaField = value;
                    this.RaisePropertyChanged("BuildingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BuildingId {
            get {
                return this.BuildingIdField;
            }
            set {
                if ((this.BuildingIdField.Equals(value) != true)) {
                    this.BuildingIdField = value;
                    this.RaisePropertyChanged("BuildingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clerk {
            get {
                return this.ClerkField;
            }
            set {
                if ((object.ReferenceEquals(this.ClerkField, value) != true)) {
                    this.ClerkField = value;
                    this.RaisePropertyChanged("Clerk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditRating {
            get {
                return this.CreditRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditRatingField, value) != true)) {
                    this.CreditRatingField = value;
                    this.RaisePropertyChanged("CreditRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FirstPay {
            get {
                return this.FirstPayField;
            }
            set {
                if ((this.FirstPayField.Equals(value) != true)) {
                    this.FirstPayField = value;
                    this.RaisePropertyChanged("FirstPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorNumber {
            get {
                return this.FloorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorNumberField, value) != true)) {
                    this.FloorNumberField = value;
                    this.RaisePropertyChanged("FloorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Installment {
            get {
                return this.InstallmentField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallmentField, value) != true)) {
                    this.InstallmentField = value;
                    this.RaisePropertyChanged("Installment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LineOfcredit {
            get {
                return this.LineOfcreditField;
            }
            set {
                if ((this.LineOfcreditField.Equals(value) != true)) {
                    this.LineOfcreditField = value;
                    this.RaisePropertyChanged("LineOfcredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LoanAge {
            get {
                return this.LoanAgeField;
            }
            set {
                if ((this.LoanAgeField.Equals(value) != true)) {
                    this.LoanAgeField = value;
                    this.RaisePropertyChanged("LoanAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LoanBalance {
            get {
                return this.LoanBalanceField;
            }
            set {
                if ((this.LoanBalanceField.Equals(value) != true)) {
                    this.LoanBalanceField = value;
                    this.RaisePropertyChanged("LoanBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanCardID {
            get {
                return this.LoanCardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanCardIDField, value) != true)) {
                    this.LoanCardIDField = value;
                    this.RaisePropertyChanged("LoanCardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LoanCardinalNumber {
            get {
                return this.LoanCardinalNumberField;
            }
            set {
                if ((this.LoanCardinalNumberField.Equals(value) != true)) {
                    this.LoanCardinalNumberField = value;
                    this.RaisePropertyChanged("LoanCardinalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanCensus {
            get {
                return this.LoanCensusField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanCensusField, value) != true)) {
                    this.LoanCensusField = value;
                    this.RaisePropertyChanged("LoanCensus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanCompany {
            get {
                return this.LoanCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanCompanyField, value) != true)) {
                    this.LoanCompanyField = value;
                    this.RaisePropertyChanged("LoanCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LoanDate {
            get {
                return this.LoanDateField;
            }
            set {
                if ((this.LoanDateField.Equals(value) != true)) {
                    this.LoanDateField = value;
                    this.RaisePropertyChanged("LoanDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanEducationalBackground {
            get {
                return this.LoanEducationalBackgroundField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanEducationalBackgroundField, value) != true)) {
                    this.LoanEducationalBackgroundField = value;
                    this.RaisePropertyChanged("LoanEducationalBackground");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LoanInterestRate {
            get {
                return this.LoanInterestRateField;
            }
            set {
                if ((this.LoanInterestRateField.Equals(value) != true)) {
                    this.LoanInterestRateField = value;
                    this.RaisePropertyChanged("LoanInterestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanMarriage {
            get {
                return this.LoanMarriageField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanMarriageField, value) != true)) {
                    this.LoanMarriageField = value;
                    this.RaisePropertyChanged("LoanMarriage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanPeople {
            get {
                return this.LoanPeopleField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanPeopleField, value) != true)) {
                    this.LoanPeopleField = value;
                    this.RaisePropertyChanged("LoanPeople");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanProfession {
            get {
                return this.LoanProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanProfessionField, value) != true)) {
                    this.LoanProfessionField = value;
                    this.RaisePropertyChanged("LoanProfession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LoanSalary {
            get {
                return this.LoanSalaryField;
            }
            set {
                if ((this.LoanSalaryField.Equals(value) != true)) {
                    this.LoanSalaryField = value;
                    this.RaisePropertyChanged("LoanSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LoanSex {
            get {
                return this.LoanSexField;
            }
            set {
                if ((this.LoanSexField.Equals(value) != true)) {
                    this.LoanSexField = value;
                    this.RaisePropertyChanged("LoanSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LoanYear {
            get {
                return this.LoanYearField;
            }
            set {
                if ((this.LoanYearField.Equals(value) != true)) {
                    this.LoanYearField = value;
                    this.RaisePropertyChanged("LoanYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MonthsPay {
            get {
                return this.MonthsPayField;
            }
            set {
                if ((this.MonthsPayField.Equals(value) != true)) {
                    this.MonthsPayField = value;
                    this.RaisePropertyChanged("MonthsPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectAddress {
            get {
                return this.ProjectAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectAddressField, value) != true)) {
                    this.ProjectAddressField = value;
                    this.RaisePropertyChanged("ProjectAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectType {
            get {
                return this.ProjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectTypeField, value) != true)) {
                    this.ProjectTypeField = value;
                    this.RaisePropertyChanged("ProjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurposeCode {
            get {
                return this.PurposeCodeField;
            }
            set {
                if ((this.PurposeCodeField.Equals(value) != true)) {
                    this.PurposeCodeField = value;
                    this.RaisePropertyChanged("PurposeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road {
            get {
                return this.RoadField;
            }
            set {
                if ((object.ReferenceEquals(this.RoadField, value) != true)) {
                    this.RoadField = value;
                    this.RaisePropertyChanged("Road");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoadNumber {
            get {
                return this.RoadNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoadNumberField, value) != true)) {
                    this.RoadNumberField = value;
                    this.RaisePropertyChanged("RoadNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubAreaId {
            get {
                return this.SubAreaIdField;
            }
            set {
                if ((this.SubAreaIdField.Equals(value) != true)) {
                    this.SubAreaIdField = value;
                    this.RaisePropertyChanged("SubAreaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FxtCollateral.IFxtCollaterals")]
    public interface IFxtCollaterals {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFxtCollaterals/Test", ReplyAction="http://tempuri.org/IFxtCollaterals/TestResponse")]
        string Test(FxtService.Proxy.FxtCollateral.DataCollateral dataCollateral);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFxtCollateralsChannel : FxtService.Proxy.FxtCollateral.IFxtCollaterals, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FxtCollateralsClient : System.ServiceModel.ClientBase<FxtService.Proxy.FxtCollateral.IFxtCollaterals>, FxtService.Proxy.FxtCollateral.IFxtCollaterals {
        
        public FxtCollateralsClient() {
        }
        
        public FxtCollateralsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FxtCollateralsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FxtCollateralsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FxtCollateralsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test(FxtService.Proxy.FxtCollateral.DataCollateral dataCollateral) {
            return base.Channel.Test(dataCollateral);
        }
    }
}
