//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace KSWF.WFM.BLL.MateService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSchoolDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSchoolInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSchoolsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCatalogkDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::KSWF.WFM.BLL.Properties.Settings.Default.KSWF_WFM_BLL_MateService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMetadataCompletedEventHandler GetMetadataCompleted;
        
        /// <remarks/>
        public event GetSchoolDataCompletedEventHandler GetSchoolDataCompleted;
        
        /// <remarks/>
        public event GetSchoolInfoCompletedEventHandler GetSchoolInfoCompleted;
        
        /// <remarks/>
        public event GetSchoolsInfoCompletedEventHandler GetSchoolsInfoCompleted;
        
        /// <remarks/>
        public event GetAreaDataCompletedEventHandler GetAreaDataCompleted;
        
        /// <remarks/>
        public event GetAreaInfoCompletedEventHandler GetAreaInfoCompleted;
        
        /// <remarks/>
        public event GetBookDataCompletedEventHandler GetBookDataCompleted;
        
        /// <remarks/>
        public event GetCatalogkDataCompletedEventHandler GetCatalogkDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMetadata", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMetadata(string tableKey) {
            object[] results = this.Invoke("GetMetadata", new object[] {
                        tableKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataAsync(string tableKey) {
            this.GetMetadataAsync(tableKey, null);
        }
        
        /// <remarks/>
        public void GetMetadataAsync(string tableKey, object userState) {
            if ((this.GetMetadataOperationCompleted == null)) {
                this.GetMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataOperationCompleted);
            }
            this.InvokeAsync("GetMetadata", new object[] {
                        tableKey}, this.GetMetadataOperationCompleted, userState);
        }
        
        private void OnGetMetadataOperationCompleted(object arg) {
            if ((this.GetMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataCompleted(this, new GetMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSchoolData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSchoolData(string districtID, string townsID, string schoolName) {
            object[] results = this.Invoke("GetSchoolData", new object[] {
                        districtID,
                        townsID,
                        schoolName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSchoolDataAsync(string districtID, string townsID, string schoolName) {
            this.GetSchoolDataAsync(districtID, townsID, schoolName, null);
        }
        
        /// <remarks/>
        public void GetSchoolDataAsync(string districtID, string townsID, string schoolName, object userState) {
            if ((this.GetSchoolDataOperationCompleted == null)) {
                this.GetSchoolDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSchoolDataOperationCompleted);
            }
            this.InvokeAsync("GetSchoolData", new object[] {
                        districtID,
                        townsID,
                        schoolName}, this.GetSchoolDataOperationCompleted, userState);
        }
        
        private void OnGetSchoolDataOperationCompleted(object arg) {
            if ((this.GetSchoolDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSchoolDataCompleted(this, new GetSchoolDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSchoolInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSchoolInfo(int schoolID) {
            object[] results = this.Invoke("GetSchoolInfo", new object[] {
                        schoolID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSchoolInfoAsync(int schoolID) {
            this.GetSchoolInfoAsync(schoolID, null);
        }
        
        /// <remarks/>
        public void GetSchoolInfoAsync(int schoolID, object userState) {
            if ((this.GetSchoolInfoOperationCompleted == null)) {
                this.GetSchoolInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSchoolInfoOperationCompleted);
            }
            this.InvokeAsync("GetSchoolInfo", new object[] {
                        schoolID}, this.GetSchoolInfoOperationCompleted, userState);
        }
        
        private void OnGetSchoolInfoOperationCompleted(object arg) {
            if ((this.GetSchoolInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSchoolInfoCompleted(this, new GetSchoolInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSchoolsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSchoolsInfo(int[] schoolID) {
            object[] results = this.Invoke("GetSchoolsInfo", new object[] {
                        schoolID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSchoolsInfoAsync(int[] schoolID) {
            this.GetSchoolsInfoAsync(schoolID, null);
        }
        
        /// <remarks/>
        public void GetSchoolsInfoAsync(int[] schoolID, object userState) {
            if ((this.GetSchoolsInfoOperationCompleted == null)) {
                this.GetSchoolsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSchoolsInfoOperationCompleted);
            }
            this.InvokeAsync("GetSchoolsInfo", new object[] {
                        schoolID}, this.GetSchoolsInfoOperationCompleted, userState);
        }
        
        private void OnGetSchoolsInfoOperationCompleted(object arg) {
            if ((this.GetSchoolsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSchoolsInfoCompleted(this, new GetSchoolsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaData(int parentID) {
            object[] results = this.Invoke("GetAreaData", new object[] {
                        parentID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaDataAsync(int parentID) {
            this.GetAreaDataAsync(parentID, null);
        }
        
        /// <remarks/>
        public void GetAreaDataAsync(int parentID, object userState) {
            if ((this.GetAreaDataOperationCompleted == null)) {
                this.GetAreaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaDataOperationCompleted);
            }
            this.InvokeAsync("GetAreaData", new object[] {
                        parentID}, this.GetAreaDataOperationCompleted, userState);
        }
        
        private void OnGetAreaDataOperationCompleted(object arg) {
            if ((this.GetAreaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaDataCompleted(this, new GetAreaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaInfo(int AreaID) {
            object[] results = this.Invoke("GetAreaInfo", new object[] {
                        AreaID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaInfoAsync(int AreaID) {
            this.GetAreaInfoAsync(AreaID, null);
        }
        
        /// <remarks/>
        public void GetAreaInfoAsync(int AreaID, object userState) {
            if ((this.GetAreaInfoOperationCompleted == null)) {
                this.GetAreaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaInfoOperationCompleted);
            }
            this.InvokeAsync("GetAreaInfo", new object[] {
                        AreaID}, this.GetAreaInfoOperationCompleted, userState);
        }
        
        private void OnGetAreaInfoOperationCompleted(object arg) {
            if ((this.GetAreaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaInfoCompleted(this, new GetAreaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBookData(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            object[] results = this.Invoke("GetBookData", new object[] {
                        Stage,
                        Grade,
                        Subject,
                        Edition,
                        Booklet});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            this.GetBookDataAsync(Stage, Grade, Subject, Edition, Booklet, null);
        }
        
        /// <remarks/>
        public void GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet, object userState) {
            if ((this.GetBookDataOperationCompleted == null)) {
                this.GetBookDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookDataOperationCompleted);
            }
            this.InvokeAsync("GetBookData", new object[] {
                        Stage,
                        Grade,
                        Subject,
                        Edition,
                        Booklet}, this.GetBookDataOperationCompleted, userState);
        }
        
        private void OnGetBookDataOperationCompleted(object arg) {
            if ((this.GetBookDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookDataCompleted(this, new GetBookDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCatalogkData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCatalogkData(string BookId) {
            object[] results = this.Invoke("GetCatalogkData", new object[] {
                        BookId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCatalogkDataAsync(string BookId) {
            this.GetCatalogkDataAsync(BookId, null);
        }
        
        /// <remarks/>
        public void GetCatalogkDataAsync(string BookId, object userState) {
            if ((this.GetCatalogkDataOperationCompleted == null)) {
                this.GetCatalogkDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCatalogkDataOperationCompleted);
            }
            this.InvokeAsync("GetCatalogkData", new object[] {
                        BookId}, this.GetCatalogkDataOperationCompleted, userState);
        }
        
        private void OnGetCatalogkDataOperationCompleted(object arg) {
            if ((this.GetCatalogkDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCatalogkDataCompleted(this, new GetCatalogkDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetMetadataCompletedEventHandler(object sender, GetMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetSchoolDataCompletedEventHandler(object sender, GetSchoolDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSchoolDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSchoolDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetSchoolInfoCompletedEventHandler(object sender, GetSchoolInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSchoolInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSchoolInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetSchoolsInfoCompletedEventHandler(object sender, GetSchoolsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSchoolsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSchoolsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetAreaDataCompletedEventHandler(object sender, GetAreaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetAreaInfoCompletedEventHandler(object sender, GetAreaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetBookDataCompletedEventHandler(object sender, GetBookDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetCatalogkDataCompletedEventHandler(object sender, GetCatalogkDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCatalogkDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCatalogkDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591