//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXT.VQ.VQCenter.VQCenterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyMain", Namespace="http://schemas.datacontract.org/2004/07/VQOperatCenter.Entity")]
    [System.SerializableAttribute()]
    public partial class PropertyMain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caseidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int entrustsourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int entrusttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FXT.VQ.VQCenter.VQCenterService.Property[] propertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serialidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caseid {
            get {
                return this.caseidField;
            }
            set {
                if ((object.ReferenceEquals(this.caseidField, value) != true)) {
                    this.caseidField = value;
                    this.RaisePropertyChanged("caseid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyid {
            get {
                return this.companyidField;
            }
            set {
                if ((this.companyidField.Equals(value) != true)) {
                    this.companyidField = value;
                    this.RaisePropertyChanged("companyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int entrustsource {
            get {
                return this.entrustsourceField;
            }
            set {
                if ((this.entrustsourceField.Equals(value) != true)) {
                    this.entrustsourceField = value;
                    this.RaisePropertyChanged("entrustsource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int entrusttype {
            get {
                return this.entrusttypeField;
            }
            set {
                if ((this.entrusttypeField.Equals(value) != true)) {
                    this.entrusttypeField = value;
                    this.RaisePropertyChanged("entrusttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FXT.VQ.VQCenter.VQCenterService.Property[] property {
            get {
                return this.propertyField;
            }
            set {
                if ((object.ReferenceEquals(this.propertyField, value) != true)) {
                    this.propertyField = value;
                    this.RaisePropertyChanged("property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serialid {
            get {
                return this.serialidField;
            }
            set {
                if ((object.ReferenceEquals(this.serialidField, value) != true)) {
                    this.serialidField = value;
                    this.RaisePropertyChanged("serialid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.datacontract.org/2004/07/VQOperatCenter.Entity")]
    [System.SerializableAttribute()]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> areaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areanameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> artifpricedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> artifpriceuseridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> artiftotalpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> artifunpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> autopricedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> autototalpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> autounpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankpropertyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankserialidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> buildingareaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> buildingidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string buildingnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cityidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string citynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> enddateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string floornumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string housecardnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> houseidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string housenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string housestateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string housetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> issubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string landtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> projectidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string projectnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int propertypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> provinceidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provincenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int querypricetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> regdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> totalfloorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> areaid {
            get {
                return this.areaidField;
            }
            set {
                if ((this.areaidField.Equals(value) != true)) {
                    this.areaidField = value;
                    this.RaisePropertyChanged("areaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string areaname {
            get {
                return this.areanameField;
            }
            set {
                if ((object.ReferenceEquals(this.areanameField, value) != true)) {
                    this.areanameField = value;
                    this.RaisePropertyChanged("areaname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> artifpricedate {
            get {
                return this.artifpricedateField;
            }
            set {
                if ((this.artifpricedateField.Equals(value) != true)) {
                    this.artifpricedateField = value;
                    this.RaisePropertyChanged("artifpricedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> artifpriceuserid {
            get {
                return this.artifpriceuseridField;
            }
            set {
                if ((this.artifpriceuseridField.Equals(value) != true)) {
                    this.artifpriceuseridField = value;
                    this.RaisePropertyChanged("artifpriceuserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> artiftotalprice {
            get {
                return this.artiftotalpriceField;
            }
            set {
                if ((this.artiftotalpriceField.Equals(value) != true)) {
                    this.artiftotalpriceField = value;
                    this.RaisePropertyChanged("artiftotalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> artifunprice {
            get {
                return this.artifunpriceField;
            }
            set {
                if ((this.artifunpriceField.Equals(value) != true)) {
                    this.artifunpriceField = value;
                    this.RaisePropertyChanged("artifunprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> autopricedate {
            get {
                return this.autopricedateField;
            }
            set {
                if ((this.autopricedateField.Equals(value) != true)) {
                    this.autopricedateField = value;
                    this.RaisePropertyChanged("autopricedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> autototalprice {
            get {
                return this.autototalpriceField;
            }
            set {
                if ((this.autototalpriceField.Equals(value) != true)) {
                    this.autototalpriceField = value;
                    this.RaisePropertyChanged("autototalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> autounprice {
            get {
                return this.autounpriceField;
            }
            set {
                if ((this.autounpriceField.Equals(value) != true)) {
                    this.autounpriceField = value;
                    this.RaisePropertyChanged("autounprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankpropertyid {
            get {
                return this.bankpropertyidField;
            }
            set {
                if ((object.ReferenceEquals(this.bankpropertyidField, value) != true)) {
                    this.bankpropertyidField = value;
                    this.RaisePropertyChanged("bankpropertyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankserialid {
            get {
                return this.bankserialidField;
            }
            set {
                if ((object.ReferenceEquals(this.bankserialidField, value) != true)) {
                    this.bankserialidField = value;
                    this.RaisePropertyChanged("bankserialid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> buildingarea {
            get {
                return this.buildingareaField;
            }
            set {
                if ((this.buildingareaField.Equals(value) != true)) {
                    this.buildingareaField = value;
                    this.RaisePropertyChanged("buildingarea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> buildingid {
            get {
                return this.buildingidField;
            }
            set {
                if ((this.buildingidField.Equals(value) != true)) {
                    this.buildingidField = value;
                    this.RaisePropertyChanged("buildingid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string buildingname {
            get {
                return this.buildingnameField;
            }
            set {
                if ((object.ReferenceEquals(this.buildingnameField, value) != true)) {
                    this.buildingnameField = value;
                    this.RaisePropertyChanged("buildingname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cityid {
            get {
                return this.cityidField;
            }
            set {
                if ((this.cityidField.Equals(value) != true)) {
                    this.cityidField = value;
                    this.RaisePropertyChanged("cityid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cityname {
            get {
                return this.citynameField;
            }
            set {
                if ((object.ReferenceEquals(this.citynameField, value) != true)) {
                    this.citynameField = value;
                    this.RaisePropertyChanged("cityname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> enddate {
            get {
                return this.enddateField;
            }
            set {
                if ((this.enddateField.Equals(value) != true)) {
                    this.enddateField = value;
                    this.RaisePropertyChanged("enddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string floornumber {
            get {
                return this.floornumberField;
            }
            set {
                if ((object.ReferenceEquals(this.floornumberField, value) != true)) {
                    this.floornumberField = value;
                    this.RaisePropertyChanged("floornumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string housecardno {
            get {
                return this.housecardnoField;
            }
            set {
                if ((object.ReferenceEquals(this.housecardnoField, value) != true)) {
                    this.housecardnoField = value;
                    this.RaisePropertyChanged("housecardno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> houseid {
            get {
                return this.houseidField;
            }
            set {
                if ((this.houseidField.Equals(value) != true)) {
                    this.houseidField = value;
                    this.RaisePropertyChanged("houseid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string housename {
            get {
                return this.housenameField;
            }
            set {
                if ((object.ReferenceEquals(this.housenameField, value) != true)) {
                    this.housenameField = value;
                    this.RaisePropertyChanged("housename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string housestate {
            get {
                return this.housestateField;
            }
            set {
                if ((object.ReferenceEquals(this.housestateField, value) != true)) {
                    this.housestateField = value;
                    this.RaisePropertyChanged("housestate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string housetype {
            get {
                return this.housetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.housetypeField, value) != true)) {
                    this.housetypeField = value;
                    this.RaisePropertyChanged("housetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> issub {
            get {
                return this.issubField;
            }
            set {
                if ((this.issubField.Equals(value) != true)) {
                    this.issubField = value;
                    this.RaisePropertyChanged("issub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string landtype {
            get {
                return this.landtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.landtypeField, value) != true)) {
                    this.landtypeField = value;
                    this.RaisePropertyChanged("landtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> projectid {
            get {
                return this.projectidField;
            }
            set {
                if ((this.projectidField.Equals(value) != true)) {
                    this.projectidField = value;
                    this.RaisePropertyChanged("projectid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string projectname {
            get {
                return this.projectnameField;
            }
            set {
                if ((object.ReferenceEquals(this.projectnameField, value) != true)) {
                    this.projectnameField = value;
                    this.RaisePropertyChanged("projectname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int propertype {
            get {
                return this.propertypeField;
            }
            set {
                if ((this.propertypeField.Equals(value) != true)) {
                    this.propertypeField = value;
                    this.RaisePropertyChanged("propertype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> provinceid {
            get {
                return this.provinceidField;
            }
            set {
                if ((this.provinceidField.Equals(value) != true)) {
                    this.provinceidField = value;
                    this.RaisePropertyChanged("provinceid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincename {
            get {
                return this.provincenameField;
            }
            set {
                if ((object.ReferenceEquals(this.provincenameField, value) != true)) {
                    this.provincenameField = value;
                    this.RaisePropertyChanged("provincename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int querypricetype {
            get {
                return this.querypricetypeField;
            }
            set {
                if ((this.querypricetypeField.Equals(value) != true)) {
                    this.querypricetypeField = value;
                    this.RaisePropertyChanged("querypricetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> regdate {
            get {
                return this.regdateField;
            }
            set {
                if ((this.regdateField.Equals(value) != true)) {
                    this.regdateField = value;
                    this.RaisePropertyChanged("regdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string road {
            get {
                return this.roadField;
            }
            set {
                if ((object.ReferenceEquals(this.roadField, value) != true)) {
                    this.roadField = value;
                    this.RaisePropertyChanged("road");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> totalfloor {
            get {
                return this.totalfloorField;
            }
            set {
                if ((this.totalfloorField.Equals(value) != true)) {
                    this.totalfloorField = value;
                    this.RaisePropertyChanged("totalfloor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanExcelParam", Namespace="http://schemas.datacontract.org/2004/07/VQOperatCenter.Entity")]
    [System.SerializableAttribute()]
    public partial class LoanExcelParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BusinessTypeDesck__BackingFieldField;
        
        private int BusinessTypek__BackingFieldField;
        
        private int bankidk__BackingFieldField;
        
        private FXT.VQ.VQCenter.VQCenterService.LoanExcelModel[] excellistk__BackingFieldField;
        
        private string excelmappathk__BackingFieldField;
        
        private string excelpathk__BackingFieldField;
        
        private string ssssk__BackingFieldField;
        
        private string subcompanyk__BackingFieldField;
        
        private int subcompanyidk__BackingFieldField;
        
        private int useridk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessTypeDesc>k__BackingField", IsRequired=true)]
        public string BusinessTypeDesck__BackingField {
            get {
                return this.BusinessTypeDesck__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTypeDesck__BackingFieldField, value) != true)) {
                    this.BusinessTypeDesck__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessTypeDesck__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BusinessType>k__BackingField", IsRequired=true)]
        public int BusinessTypek__BackingField {
            get {
                return this.BusinessTypek__BackingFieldField;
            }
            set {
                if ((this.BusinessTypek__BackingFieldField.Equals(value) != true)) {
                    this.BusinessTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("BusinessTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bankid>k__BackingField", IsRequired=true)]
        public int bankidk__BackingField {
            get {
                return this.bankidk__BackingFieldField;
            }
            set {
                if ((this.bankidk__BackingFieldField.Equals(value) != true)) {
                    this.bankidk__BackingFieldField = value;
                    this.RaisePropertyChanged("bankidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<excellist>k__BackingField", IsRequired=true)]
        public FXT.VQ.VQCenter.VQCenterService.LoanExcelModel[] excellistk__BackingField {
            get {
                return this.excellistk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.excellistk__BackingFieldField, value) != true)) {
                    this.excellistk__BackingFieldField = value;
                    this.RaisePropertyChanged("excellistk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<excelmappath>k__BackingField", IsRequired=true)]
        public string excelmappathk__BackingField {
            get {
                return this.excelmappathk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.excelmappathk__BackingFieldField, value) != true)) {
                    this.excelmappathk__BackingFieldField = value;
                    this.RaisePropertyChanged("excelmappathk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<excelpath>k__BackingField", IsRequired=true)]
        public string excelpathk__BackingField {
            get {
                return this.excelpathk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.excelpathk__BackingFieldField, value) != true)) {
                    this.excelpathk__BackingFieldField = value;
                    this.RaisePropertyChanged("excelpathk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ssss>k__BackingField", IsRequired=true)]
        public string ssssk__BackingField {
            get {
                return this.ssssk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ssssk__BackingFieldField, value) != true)) {
                    this.ssssk__BackingFieldField = value;
                    this.RaisePropertyChanged("ssssk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<subcompany>k__BackingField", IsRequired=true)]
        public string subcompanyk__BackingField {
            get {
                return this.subcompanyk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.subcompanyk__BackingFieldField, value) != true)) {
                    this.subcompanyk__BackingFieldField = value;
                    this.RaisePropertyChanged("subcompanyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<subcompanyid>k__BackingField", IsRequired=true)]
        public int subcompanyidk__BackingField {
            get {
                return this.subcompanyidk__BackingFieldField;
            }
            set {
                if ((this.subcompanyidk__BackingFieldField.Equals(value) != true)) {
                    this.subcompanyidk__BackingFieldField = value;
                    this.RaisePropertyChanged("subcompanyidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<userid>k__BackingField", IsRequired=true)]
        public int useridk__BackingField {
            get {
                return this.useridk__BackingFieldField;
            }
            set {
                if ((this.useridk__BackingFieldField.Equals(value) != true)) {
                    this.useridk__BackingFieldField = value;
                    this.RaisePropertyChanged("useridk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<username>k__BackingField", IsRequired=true)]
        public string usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.usernamek__BackingFieldField, value) != true)) {
                    this.usernamek__BackingFieldField = value;
                    this.RaisePropertyChanged("usernamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanExcelModel", Namespace="http://schemas.datacontract.org/2004/07/VQOperatCenter.Entity")]
    [System.SerializableAttribute()]
    public partial class LoanExcelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string bus_areanamek__BackingFieldField;
        
        private string bus_branchk__BackingFieldField;
        
        private string bus_citynamek__BackingFieldField;
        
        private string bus_collateraladdressk__BackingFieldField;
        
        private System.Nullable<decimal> bus_collateralareak__BackingFieldField;
        
        private string bus_collateralidk__BackingFieldField;
        
        private string bus_collateralnamek__BackingFieldField;
        
        private string bus_collateraltypek__BackingFieldField;
        
        private System.Nullable<int> bus_lenderagek__BackingFieldField;
        
        private System.Nullable<decimal> bus_loanbalancek__BackingFieldField;
        
        private System.Nullable<decimal> bus_loancreditsk__BackingFieldField;
        
        private System.Nullable<decimal> bus_loanpercentk__BackingFieldField;
        
        private System.Nullable<int> bus_loanyearsk__BackingFieldField;
        
        private string bus_onebranchk__BackingFieldField;
        
        private System.Nullable<decimal> bus_originalratesk__BackingFieldField;
        
        private System.Nullable<decimal> bus_originalvaluationk__BackingFieldField;
        
        private System.Nullable<decimal> bus_pawnareak__BackingFieldField;
        
        private string bus_provincenamek__BackingFieldField;
        
        private string bus_twobranchk__BackingFieldField;
        
        private string errork__BackingFieldField;
        
        private int indexk__BackingFieldField;
        
        private string pawn_affiliatedprok__BackingFieldField;
        
        private System.Nullable<int> pawn_areaidk__BackingFieldField;
        
        private string pawn_areanamek__BackingFieldField;
        
        private System.Nullable<long> pawn_buildingidk__BackingFieldField;
        
        private string pawn_buildingnamek__BackingFieldField;
        
        private System.Nullable<int> pawn_cityidk__BackingFieldField;
        
        private string pawn_citynamek__BackingFieldField;
        
        private System.Nullable<System.DateTime> pawn_completiondatek__BackingFieldField;
        
        private string pawn_developersnamek__BackingFieldField;
        
        private string pawn_flatstructk__BackingFieldField;
        
        private string pawn_floornok__BackingFieldField;
        
        private System.Nullable<long> pawn_houseidk__BackingFieldField;
        
        private string pawn_housenamek__BackingFieldField;
        
        private string pawn_iscityk__BackingFieldField;
        
        private System.Nullable<decimal> pawn_latitudek__BackingFieldField;
        
        private System.Nullable<decimal> pawn_longitudek__BackingFieldField;
        
        private string pawn_numberk__BackingFieldField;
        
        private string pawn_pawnnamek__BackingFieldField;
        
        private string pawn_propertyaddressk__BackingFieldField;
        
        private System.Nullable<long> pawn_propertyidk__BackingFieldField;
        
        private string pawn_propertynamek__BackingFieldField;
        
        private string pawn_propertytypek__BackingFieldField;
        
        private System.Nullable<int> pawn_provinceidk__BackingFieldField;
        
        private string pawn_provincenamek__BackingFieldField;
        
        private string pawn_roadk__BackingFieldField;
        
        private string pawn_stagingk__BackingFieldField;
        
        private string project_nok__BackingFieldField;
        
        private string task_nok__BackingFieldField;
        
        private System.Nullable<decimal> work_currassesstotalpricek__BackingFieldField;
        
        private System.Nullable<decimal> work_currassesstotalvalk__BackingFieldField;
        
        private System.Nullable<decimal> work_currassessunpricek__BackingFieldField;
        
        private System.Nullable<decimal> work_currratesk__BackingFieldField;
        
        private System.Nullable<System.DateTime> work_loantaskadddatek__BackingFieldField;
        
        private System.Nullable<System.DateTime> work_loantasksplitdatek__BackingFieldField;
        
        private System.Nullable<System.DateTime> work_loantasksuccessdatek__BackingFieldField;
        
        private string work_remarkk__BackingFieldField;
        
        private string work_suppliernamek__BackingFieldField;
        
        private System.Nullable<int> work_surveyidk__BackingFieldField;
        
        private string work_worknamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_areaname>k__BackingField", IsRequired=true)]
        public string bus_areanamek__BackingField {
            get {
                return this.bus_areanamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_areanamek__BackingFieldField, value) != true)) {
                    this.bus_areanamek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_areanamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_branch>k__BackingField", IsRequired=true)]
        public string bus_branchk__BackingField {
            get {
                return this.bus_branchk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_branchk__BackingFieldField, value) != true)) {
                    this.bus_branchk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_branchk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_cityname>k__BackingField", IsRequired=true)]
        public string bus_citynamek__BackingField {
            get {
                return this.bus_citynamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_citynamek__BackingFieldField, value) != true)) {
                    this.bus_citynamek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_citynamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_collateraladdress>k__BackingField", IsRequired=true)]
        public string bus_collateraladdressk__BackingField {
            get {
                return this.bus_collateraladdressk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_collateraladdressk__BackingFieldField, value) != true)) {
                    this.bus_collateraladdressk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_collateraladdressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_collateralarea>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_collateralareak__BackingField {
            get {
                return this.bus_collateralareak__BackingFieldField;
            }
            set {
                if ((this.bus_collateralareak__BackingFieldField.Equals(value) != true)) {
                    this.bus_collateralareak__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_collateralareak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_collateralid>k__BackingField", IsRequired=true)]
        public string bus_collateralidk__BackingField {
            get {
                return this.bus_collateralidk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_collateralidk__BackingFieldField, value) != true)) {
                    this.bus_collateralidk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_collateralidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_collateralname>k__BackingField", IsRequired=true)]
        public string bus_collateralnamek__BackingField {
            get {
                return this.bus_collateralnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_collateralnamek__BackingFieldField, value) != true)) {
                    this.bus_collateralnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_collateralnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_collateraltype>k__BackingField", IsRequired=true)]
        public string bus_collateraltypek__BackingField {
            get {
                return this.bus_collateraltypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_collateraltypek__BackingFieldField, value) != true)) {
                    this.bus_collateraltypek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_collateraltypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_lenderage>k__BackingField", IsRequired=true)]
        public System.Nullable<int> bus_lenderagek__BackingField {
            get {
                return this.bus_lenderagek__BackingFieldField;
            }
            set {
                if ((this.bus_lenderagek__BackingFieldField.Equals(value) != true)) {
                    this.bus_lenderagek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_lenderagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_loanbalance>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_loanbalancek__BackingField {
            get {
                return this.bus_loanbalancek__BackingFieldField;
            }
            set {
                if ((this.bus_loanbalancek__BackingFieldField.Equals(value) != true)) {
                    this.bus_loanbalancek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_loanbalancek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_loancredits>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_loancreditsk__BackingField {
            get {
                return this.bus_loancreditsk__BackingFieldField;
            }
            set {
                if ((this.bus_loancreditsk__BackingFieldField.Equals(value) != true)) {
                    this.bus_loancreditsk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_loancreditsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_loanpercent>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_loanpercentk__BackingField {
            get {
                return this.bus_loanpercentk__BackingFieldField;
            }
            set {
                if ((this.bus_loanpercentk__BackingFieldField.Equals(value) != true)) {
                    this.bus_loanpercentk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_loanpercentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_loanyears>k__BackingField", IsRequired=true)]
        public System.Nullable<int> bus_loanyearsk__BackingField {
            get {
                return this.bus_loanyearsk__BackingFieldField;
            }
            set {
                if ((this.bus_loanyearsk__BackingFieldField.Equals(value) != true)) {
                    this.bus_loanyearsk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_loanyearsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_onebranch>k__BackingField", IsRequired=true)]
        public string bus_onebranchk__BackingField {
            get {
                return this.bus_onebranchk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_onebranchk__BackingFieldField, value) != true)) {
                    this.bus_onebranchk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_onebranchk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_originalrates>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_originalratesk__BackingField {
            get {
                return this.bus_originalratesk__BackingFieldField;
            }
            set {
                if ((this.bus_originalratesk__BackingFieldField.Equals(value) != true)) {
                    this.bus_originalratesk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_originalratesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_originalvaluation>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_originalvaluationk__BackingField {
            get {
                return this.bus_originalvaluationk__BackingFieldField;
            }
            set {
                if ((this.bus_originalvaluationk__BackingFieldField.Equals(value) != true)) {
                    this.bus_originalvaluationk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_originalvaluationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_pawnarea>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> bus_pawnareak__BackingField {
            get {
                return this.bus_pawnareak__BackingFieldField;
            }
            set {
                if ((this.bus_pawnareak__BackingFieldField.Equals(value) != true)) {
                    this.bus_pawnareak__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_pawnareak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_provincename>k__BackingField", IsRequired=true)]
        public string bus_provincenamek__BackingField {
            get {
                return this.bus_provincenamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_provincenamek__BackingFieldField, value) != true)) {
                    this.bus_provincenamek__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_provincenamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<bus_twobranch>k__BackingField", IsRequired=true)]
        public string bus_twobranchk__BackingField {
            get {
                return this.bus_twobranchk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.bus_twobranchk__BackingFieldField, value) != true)) {
                    this.bus_twobranchk__BackingFieldField = value;
                    this.RaisePropertyChanged("bus_twobranchk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<error>k__BackingField", IsRequired=true)]
        public string errork__BackingField {
            get {
                return this.errork__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.errork__BackingFieldField, value) != true)) {
                    this.errork__BackingFieldField = value;
                    this.RaisePropertyChanged("errork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<index>k__BackingField", IsRequired=true)]
        public int indexk__BackingField {
            get {
                return this.indexk__BackingFieldField;
            }
            set {
                if ((this.indexk__BackingFieldField.Equals(value) != true)) {
                    this.indexk__BackingFieldField = value;
                    this.RaisePropertyChanged("indexk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_affiliatedpro>k__BackingField", IsRequired=true)]
        public string pawn_affiliatedprok__BackingField {
            get {
                return this.pawn_affiliatedprok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_affiliatedprok__BackingFieldField, value) != true)) {
                    this.pawn_affiliatedprok__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_affiliatedprok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_areaid>k__BackingField", IsRequired=true)]
        public System.Nullable<int> pawn_areaidk__BackingField {
            get {
                return this.pawn_areaidk__BackingFieldField;
            }
            set {
                if ((this.pawn_areaidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_areaidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_areaidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_areaname>k__BackingField", IsRequired=true)]
        public string pawn_areanamek__BackingField {
            get {
                return this.pawn_areanamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_areanamek__BackingFieldField, value) != true)) {
                    this.pawn_areanamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_areanamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_buildingid>k__BackingField", IsRequired=true)]
        public System.Nullable<long> pawn_buildingidk__BackingField {
            get {
                return this.pawn_buildingidk__BackingFieldField;
            }
            set {
                if ((this.pawn_buildingidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_buildingidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_buildingidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_buildingname>k__BackingField", IsRequired=true)]
        public string pawn_buildingnamek__BackingField {
            get {
                return this.pawn_buildingnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_buildingnamek__BackingFieldField, value) != true)) {
                    this.pawn_buildingnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_buildingnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_cityid>k__BackingField", IsRequired=true)]
        public System.Nullable<int> pawn_cityidk__BackingField {
            get {
                return this.pawn_cityidk__BackingFieldField;
            }
            set {
                if ((this.pawn_cityidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_cityidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_cityidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_cityname>k__BackingField", IsRequired=true)]
        public string pawn_citynamek__BackingField {
            get {
                return this.pawn_citynamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_citynamek__BackingFieldField, value) != true)) {
                    this.pawn_citynamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_citynamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_completiondate>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> pawn_completiondatek__BackingField {
            get {
                return this.pawn_completiondatek__BackingFieldField;
            }
            set {
                if ((this.pawn_completiondatek__BackingFieldField.Equals(value) != true)) {
                    this.pawn_completiondatek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_completiondatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_developersname>k__BackingField", IsRequired=true)]
        public string pawn_developersnamek__BackingField {
            get {
                return this.pawn_developersnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_developersnamek__BackingFieldField, value) != true)) {
                    this.pawn_developersnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_developersnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_flatstruct>k__BackingField", IsRequired=true)]
        public string pawn_flatstructk__BackingField {
            get {
                return this.pawn_flatstructk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_flatstructk__BackingFieldField, value) != true)) {
                    this.pawn_flatstructk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_flatstructk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_floorno>k__BackingField", IsRequired=true)]
        public string pawn_floornok__BackingField {
            get {
                return this.pawn_floornok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_floornok__BackingFieldField, value) != true)) {
                    this.pawn_floornok__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_floornok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_houseid>k__BackingField", IsRequired=true)]
        public System.Nullable<long> pawn_houseidk__BackingField {
            get {
                return this.pawn_houseidk__BackingFieldField;
            }
            set {
                if ((this.pawn_houseidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_houseidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_houseidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_housename>k__BackingField", IsRequired=true)]
        public string pawn_housenamek__BackingField {
            get {
                return this.pawn_housenamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_housenamek__BackingFieldField, value) != true)) {
                    this.pawn_housenamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_housenamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_iscity>k__BackingField", IsRequired=true)]
        public string pawn_iscityk__BackingField {
            get {
                return this.pawn_iscityk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_iscityk__BackingFieldField, value) != true)) {
                    this.pawn_iscityk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_iscityk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_latitude>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> pawn_latitudek__BackingField {
            get {
                return this.pawn_latitudek__BackingFieldField;
            }
            set {
                if ((this.pawn_latitudek__BackingFieldField.Equals(value) != true)) {
                    this.pawn_latitudek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_latitudek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_longitude>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> pawn_longitudek__BackingField {
            get {
                return this.pawn_longitudek__BackingFieldField;
            }
            set {
                if ((this.pawn_longitudek__BackingFieldField.Equals(value) != true)) {
                    this.pawn_longitudek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_longitudek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_number>k__BackingField", IsRequired=true)]
        public string pawn_numberk__BackingField {
            get {
                return this.pawn_numberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_numberk__BackingFieldField, value) != true)) {
                    this.pawn_numberk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_numberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_pawnname>k__BackingField", IsRequired=true)]
        public string pawn_pawnnamek__BackingField {
            get {
                return this.pawn_pawnnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_pawnnamek__BackingFieldField, value) != true)) {
                    this.pawn_pawnnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_pawnnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_propertyaddress>k__BackingField", IsRequired=true)]
        public string pawn_propertyaddressk__BackingField {
            get {
                return this.pawn_propertyaddressk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_propertyaddressk__BackingFieldField, value) != true)) {
                    this.pawn_propertyaddressk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_propertyaddressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_propertyid>k__BackingField", IsRequired=true)]
        public System.Nullable<long> pawn_propertyidk__BackingField {
            get {
                return this.pawn_propertyidk__BackingFieldField;
            }
            set {
                if ((this.pawn_propertyidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_propertyidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_propertyidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_propertyname>k__BackingField", IsRequired=true)]
        public string pawn_propertynamek__BackingField {
            get {
                return this.pawn_propertynamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_propertynamek__BackingFieldField, value) != true)) {
                    this.pawn_propertynamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_propertynamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_propertytype>k__BackingField", IsRequired=true)]
        public string pawn_propertytypek__BackingField {
            get {
                return this.pawn_propertytypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_propertytypek__BackingFieldField, value) != true)) {
                    this.pawn_propertytypek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_propertytypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_provinceid>k__BackingField", IsRequired=true)]
        public System.Nullable<int> pawn_provinceidk__BackingField {
            get {
                return this.pawn_provinceidk__BackingFieldField;
            }
            set {
                if ((this.pawn_provinceidk__BackingFieldField.Equals(value) != true)) {
                    this.pawn_provinceidk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_provinceidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_provincename>k__BackingField", IsRequired=true)]
        public string pawn_provincenamek__BackingField {
            get {
                return this.pawn_provincenamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_provincenamek__BackingFieldField, value) != true)) {
                    this.pawn_provincenamek__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_provincenamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_road>k__BackingField", IsRequired=true)]
        public string pawn_roadk__BackingField {
            get {
                return this.pawn_roadk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_roadk__BackingFieldField, value) != true)) {
                    this.pawn_roadk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_roadk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<pawn_staging>k__BackingField", IsRequired=true)]
        public string pawn_stagingk__BackingField {
            get {
                return this.pawn_stagingk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pawn_stagingk__BackingFieldField, value) != true)) {
                    this.pawn_stagingk__BackingFieldField = value;
                    this.RaisePropertyChanged("pawn_stagingk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<project_no>k__BackingField", IsRequired=true)]
        public string project_nok__BackingField {
            get {
                return this.project_nok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.project_nok__BackingFieldField, value) != true)) {
                    this.project_nok__BackingFieldField = value;
                    this.RaisePropertyChanged("project_nok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<task_no>k__BackingField", IsRequired=true)]
        public string task_nok__BackingField {
            get {
                return this.task_nok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.task_nok__BackingFieldField, value) != true)) {
                    this.task_nok__BackingFieldField = value;
                    this.RaisePropertyChanged("task_nok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_currassesstotalprice>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> work_currassesstotalpricek__BackingField {
            get {
                return this.work_currassesstotalpricek__BackingFieldField;
            }
            set {
                if ((this.work_currassesstotalpricek__BackingFieldField.Equals(value) != true)) {
                    this.work_currassesstotalpricek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_currassesstotalpricek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_currassesstotalval>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> work_currassesstotalvalk__BackingField {
            get {
                return this.work_currassesstotalvalk__BackingFieldField;
            }
            set {
                if ((this.work_currassesstotalvalk__BackingFieldField.Equals(value) != true)) {
                    this.work_currassesstotalvalk__BackingFieldField = value;
                    this.RaisePropertyChanged("work_currassesstotalvalk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_currassessunprice>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> work_currassessunpricek__BackingField {
            get {
                return this.work_currassessunpricek__BackingFieldField;
            }
            set {
                if ((this.work_currassessunpricek__BackingFieldField.Equals(value) != true)) {
                    this.work_currassessunpricek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_currassessunpricek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_currrates>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> work_currratesk__BackingField {
            get {
                return this.work_currratesk__BackingFieldField;
            }
            set {
                if ((this.work_currratesk__BackingFieldField.Equals(value) != true)) {
                    this.work_currratesk__BackingFieldField = value;
                    this.RaisePropertyChanged("work_currratesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_loantaskadddate>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> work_loantaskadddatek__BackingField {
            get {
                return this.work_loantaskadddatek__BackingFieldField;
            }
            set {
                if ((this.work_loantaskadddatek__BackingFieldField.Equals(value) != true)) {
                    this.work_loantaskadddatek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_loantaskadddatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_loantasksplitdate>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> work_loantasksplitdatek__BackingField {
            get {
                return this.work_loantasksplitdatek__BackingFieldField;
            }
            set {
                if ((this.work_loantasksplitdatek__BackingFieldField.Equals(value) != true)) {
                    this.work_loantasksplitdatek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_loantasksplitdatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_loantasksuccessdate>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> work_loantasksuccessdatek__BackingField {
            get {
                return this.work_loantasksuccessdatek__BackingFieldField;
            }
            set {
                if ((this.work_loantasksuccessdatek__BackingFieldField.Equals(value) != true)) {
                    this.work_loantasksuccessdatek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_loantasksuccessdatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_remark>k__BackingField", IsRequired=true)]
        public string work_remarkk__BackingField {
            get {
                return this.work_remarkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.work_remarkk__BackingFieldField, value) != true)) {
                    this.work_remarkk__BackingFieldField = value;
                    this.RaisePropertyChanged("work_remarkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_suppliername>k__BackingField", IsRequired=true)]
        public string work_suppliernamek__BackingField {
            get {
                return this.work_suppliernamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.work_suppliernamek__BackingFieldField, value) != true)) {
                    this.work_suppliernamek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_suppliernamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_surveyid>k__BackingField", IsRequired=true)]
        public System.Nullable<int> work_surveyidk__BackingField {
            get {
                return this.work_surveyidk__BackingFieldField;
            }
            set {
                if ((this.work_surveyidk__BackingFieldField.Equals(value) != true)) {
                    this.work_surveyidk__BackingFieldField = value;
                    this.RaisePropertyChanged("work_surveyidk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<work_workname>k__BackingField", IsRequired=true)]
        public string work_worknamek__BackingField {
            get {
                return this.work_worknamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.work_worknamek__BackingFieldField, value) != true)) {
                    this.work_worknamek__BackingFieldField = value;
                    this.RaisePropertyChanged("work_worknamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VQCenterService.IPropertyHand")]
    public interface IPropertyHand {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyHand/Start", ReplyAction="http://tempuri.org/IPropertyHand/StartResponse")]
        int Start(FXT.VQ.VQCenter.VQCenterService.PropertyMain property);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPropertyHand/LoanProcess")]
        void LoanProcess(FXT.VQ.VQCenter.VQCenterService.LoanExcelParam param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPropertyHandChannel : FXT.VQ.VQCenter.VQCenterService.IPropertyHand, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropertyHandClient : System.ServiceModel.ClientBase<FXT.VQ.VQCenter.VQCenterService.IPropertyHand>, FXT.VQ.VQCenter.VQCenterService.IPropertyHand {
        
        public PropertyHandClient() {
        }
        
        public PropertyHandClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropertyHandClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyHandClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyHandClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Start(FXT.VQ.VQCenter.VQCenterService.PropertyMain property) {
            return base.Channel.Start(property);
        }
        
        public void LoanProcess(FXT.VQ.VQCenter.VQCenterService.LoanExcelParam param) {
            base.Channel.LoanProcess(param);
        }
    }
}
