//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsun.IBS.BLL.MetadataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetadataService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tableKey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetMetadataResponse GetMetadata(Kingsun.IBS.BLL.MetadataService.GetMetadataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetMetadataResponse> GetMetadataAsync(Kingsun.IBS.BLL.MetadataService.GetMetadataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 districtID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse GetSchoolData(Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse> GetSchoolDataAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSchoolInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolInfo", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse GetSchoolInfo(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse> GetSchoolInfoAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 schoolID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolsInfo", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse GetSchoolsInfo(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse> GetSchoolsInfoAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAreaDataResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse GetAreaData(Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse> GetAreaDataAsync(Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAreaInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaInfo", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse GetAreaInfo(Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse> GetAreaInfoAsync(Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Stage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetBookDataResponse GetBookData(Kingsun.IBS.BLL.MetadataService.GetBookDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetBookDataResponse> GetBookDataAsync(Kingsun.IBS.BLL.MetadataService.GetBookDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 BookId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse GetCatalogkData(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse> GetCatalogkDataAsync(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadata", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetMetadataRequestBody Body;
        
        public GetMetadataRequest() {
        }
        
        public GetMetadataRequest(Kingsun.IBS.BLL.MetadataService.GetMetadataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMetadataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableKey;
        
        public GetMetadataRequestBody() {
        }
        
        public GetMetadataRequestBody(string tableKey) {
            this.tableKey = tableKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetMetadataResponseBody Body;
        
        public GetMetadataResponse() {
        }
        
        public GetMetadataResponse(Kingsun.IBS.BLL.MetadataService.GetMetadataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMetadataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMetadataResult;
        
        public GetMetadataResponseBody() {
        }
        
        public GetMetadataResponseBody(string GetMetadataResult) {
            this.GetMetadataResult = GetMetadataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolData", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequestBody Body;
        
        public GetSchoolDataRequest() {
        }
        
        public GetSchoolDataRequest(Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string districtID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string townsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string schoolName;
        
        public GetSchoolDataRequestBody() {
        }
        
        public GetSchoolDataRequestBody(string districtID, string townsID, string schoolName) {
            this.districtID = districtID;
            this.townsID = townsID;
            this.schoolName = schoolName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponseBody Body;
        
        public GetSchoolDataResponse() {
        }
        
        public GetSchoolDataResponse(Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchoolDataResult;
        
        public GetSchoolDataResponseBody() {
        }
        
        public GetSchoolDataResponseBody(string GetSchoolDataResult) {
            this.GetSchoolDataResult = GetSchoolDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolInfo", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequestBody Body;
        
        public GetSchoolInfoRequest() {
        }
        
        public GetSchoolInfoRequest(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int schoolID;
        
        public GetSchoolInfoRequestBody() {
        }
        
        public GetSchoolInfoRequestBody(int schoolID) {
            this.schoolID = schoolID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponseBody Body;
        
        public GetSchoolInfoResponse() {
        }
        
        public GetSchoolInfoResponse(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchoolInfoResult;
        
        public GetSchoolInfoResponseBody() {
        }
        
        public GetSchoolInfoResponseBody(string GetSchoolInfoResult) {
            this.GetSchoolInfoResult = GetSchoolInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolsInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolsInfo", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequestBody Body;
        
        public GetSchoolsInfoRequest() {
        }
        
        public GetSchoolsInfoRequest(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolsInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Kingsun.IBS.BLL.MetadataService.ArrayOfInt schoolID;
        
        public GetSchoolsInfoRequestBody() {
        }
        
        public GetSchoolsInfoRequestBody(Kingsun.IBS.BLL.MetadataService.ArrayOfInt schoolID) {
            this.schoolID = schoolID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolsInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolsInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponseBody Body;
        
        public GetSchoolsInfoResponse() {
        }
        
        public GetSchoolsInfoResponse(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolsInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchoolsInfoResult;
        
        public GetSchoolsInfoResponseBody() {
        }
        
        public GetSchoolsInfoResponseBody(string GetSchoolsInfoResult) {
            this.GetSchoolsInfoResult = GetSchoolsInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaData", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetAreaDataRequestBody Body;
        
        public GetAreaDataRequest() {
        }
        
        public GetAreaDataRequest(Kingsun.IBS.BLL.MetadataService.GetAreaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int parentID;
        
        public GetAreaDataRequestBody() {
        }
        
        public GetAreaDataRequestBody(int parentID) {
            this.parentID = parentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetAreaDataResponseBody Body;
        
        public GetAreaDataResponse() {
        }
        
        public GetAreaDataResponse(Kingsun.IBS.BLL.MetadataService.GetAreaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAreaDataResult;
        
        public GetAreaDataResponseBody() {
        }
        
        public GetAreaDataResponseBody(string GetAreaDataResult) {
            this.GetAreaDataResult = GetAreaDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaInfo", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequestBody Body;
        
        public GetAreaInfoRequest() {
        }
        
        public GetAreaInfoRequest(Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AreaID;
        
        public GetAreaInfoRequestBody() {
        }
        
        public GetAreaInfoRequestBody(int AreaID) {
            this.AreaID = AreaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponseBody Body;
        
        public GetAreaInfoResponse() {
        }
        
        public GetAreaInfoResponse(Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAreaInfoResult;
        
        public GetAreaInfoResponseBody() {
        }
        
        public GetAreaInfoResponseBody(string GetAreaInfoResult) {
            this.GetAreaInfoResult = GetAreaInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookData", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetBookDataRequestBody Body;
        
        public GetBookDataRequest() {
        }
        
        public GetBookDataRequest(Kingsun.IBS.BLL.MetadataService.GetBookDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Stage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Grade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Edition;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Booklet;
        
        public GetBookDataRequestBody() {
        }
        
        public GetBookDataRequestBody(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            this.Stage = Stage;
            this.Grade = Grade;
            this.Subject = Subject;
            this.Edition = Edition;
            this.Booklet = Booklet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetBookDataResponseBody Body;
        
        public GetBookDataResponse() {
        }
        
        public GetBookDataResponse(Kingsun.IBS.BLL.MetadataService.GetBookDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookDataResult;
        
        public GetBookDataResponseBody() {
        }
        
        public GetBookDataResponseBody(string GetBookDataResult) {
            this.GetBookDataResult = GetBookDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogkDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogkData", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequestBody Body;
        
        public GetCatalogkDataRequest() {
        }
        
        public GetCatalogkDataRequest(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogkDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookId;
        
        public GetCatalogkDataRequestBody() {
        }
        
        public GetCatalogkDataRequestBody(string BookId) {
            this.BookId = BookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogkDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogkDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponseBody Body;
        
        public GetCatalogkDataResponse() {
        }
        
        public GetCatalogkDataResponse(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogkDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCatalogkDataResult;
        
        public GetCatalogkDataResponseBody() {
        }
        
        public GetCatalogkDataResponseBody(string GetCatalogkDataResult) {
            this.GetCatalogkDataResult = GetCatalogkDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Kingsun.IBS.BLL.MetadataService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Kingsun.IBS.BLL.MetadataService.ServiceSoap>, Kingsun.IBS.BLL.MetadataService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetMetadataResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetMetadata(Kingsun.IBS.BLL.MetadataService.GetMetadataRequest request) {
            return base.Channel.GetMetadata(request);
        }
        
        public string GetMetadata(string tableKey) {
            Kingsun.IBS.BLL.MetadataService.GetMetadataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetMetadataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetMetadataRequestBody();
            inValue.Body.tableKey = tableKey;
            Kingsun.IBS.BLL.MetadataService.GetMetadataResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetMetadata(inValue);
            return retVal.Body.GetMetadataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetMetadataResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetMetadataAsync(Kingsun.IBS.BLL.MetadataService.GetMetadataRequest request) {
            return base.Channel.GetMetadataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetMetadataResponse> GetMetadataAsync(string tableKey) {
            Kingsun.IBS.BLL.MetadataService.GetMetadataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetMetadataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetMetadataRequestBody();
            inValue.Body.tableKey = tableKey;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetMetadataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolData(Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest request) {
            return base.Channel.GetSchoolData(request);
        }
        
        public string GetSchoolData(string districtID, string townsID, string schoolName) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequestBody();
            inValue.Body.districtID = districtID;
            inValue.Body.townsID = townsID;
            inValue.Body.schoolName = schoolName;
            Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolData(inValue);
            return retVal.Body.GetSchoolDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolDataAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest request) {
            return base.Channel.GetSchoolDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolDataResponse> GetSchoolDataAsync(string districtID, string townsID, string schoolName) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolDataRequestBody();
            inValue.Body.districtID = districtID;
            inValue.Body.townsID = townsID;
            inValue.Body.schoolName = schoolName;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolInfo(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest request) {
            return base.Channel.GetSchoolInfo(request);
        }
        
        public string GetSchoolInfo(int schoolID) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolInfo(inValue);
            return retVal.Body.GetSchoolInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolInfoAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest request) {
            return base.Channel.GetSchoolInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolInfoResponse> GetSchoolInfoAsync(int schoolID) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolsInfo(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest request) {
            return base.Channel.GetSchoolsInfo(request);
        }
        
        public string GetSchoolsInfo(Kingsun.IBS.BLL.MetadataService.ArrayOfInt schoolID) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolsInfo(inValue);
            return retVal.Body.GetSchoolsInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetSchoolsInfoAsync(Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest request) {
            return base.Channel.GetSchoolsInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoResponse> GetSchoolsInfoAsync(Kingsun.IBS.BLL.MetadataService.ArrayOfInt schoolID) {
            Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetSchoolsInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetSchoolsInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetAreaData(Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest request) {
            return base.Channel.GetAreaData(request);
        }
        
        public string GetAreaData(int parentID) {
            Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetAreaDataRequestBody();
            inValue.Body.parentID = parentID;
            Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetAreaData(inValue);
            return retVal.Body.GetAreaDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetAreaDataAsync(Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest request) {
            return base.Channel.GetAreaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaDataResponse> GetAreaDataAsync(int parentID) {
            Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetAreaDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetAreaDataRequestBody();
            inValue.Body.parentID = parentID;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetAreaDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetAreaInfo(Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest request) {
            return base.Channel.GetAreaInfo(request);
        }
        
        public string GetAreaInfo(int AreaID) {
            Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequestBody();
            inValue.Body.AreaID = AreaID;
            Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetAreaInfo(inValue);
            return retVal.Body.GetAreaInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetAreaInfoAsync(Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest request) {
            return base.Channel.GetAreaInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetAreaInfoResponse> GetAreaInfoAsync(int AreaID) {
            Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetAreaInfoRequestBody();
            inValue.Body.AreaID = AreaID;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetAreaInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetBookDataResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetBookData(Kingsun.IBS.BLL.MetadataService.GetBookDataRequest request) {
            return base.Channel.GetBookData(request);
        }
        
        public string GetBookData(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            Kingsun.IBS.BLL.MetadataService.GetBookDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetBookDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetBookDataRequestBody();
            inValue.Body.Stage = Stage;
            inValue.Body.Grade = Grade;
            inValue.Body.Subject = Subject;
            inValue.Body.Edition = Edition;
            inValue.Body.Booklet = Booklet;
            Kingsun.IBS.BLL.MetadataService.GetBookDataResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetBookData(inValue);
            return retVal.Body.GetBookDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetBookDataResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetBookDataAsync(Kingsun.IBS.BLL.MetadataService.GetBookDataRequest request) {
            return base.Channel.GetBookDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetBookDataResponse> GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            Kingsun.IBS.BLL.MetadataService.GetBookDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetBookDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetBookDataRequestBody();
            inValue.Body.Stage = Stage;
            inValue.Body.Grade = Grade;
            inValue.Body.Subject = Subject;
            inValue.Body.Edition = Edition;
            inValue.Body.Booklet = Booklet;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetBookDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetCatalogkData(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest request) {
            return base.Channel.GetCatalogkData(request);
        }
        
        public string GetCatalogkData(string BookId) {
            Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequestBody();
            inValue.Body.BookId = BookId;
            Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse retVal = ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetCatalogkData(inValue);
            return retVal.Body.GetCatalogkDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse> Kingsun.IBS.BLL.MetadataService.ServiceSoap.GetCatalogkDataAsync(Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest request) {
            return base.Channel.GetCatalogkDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kingsun.IBS.BLL.MetadataService.GetCatalogkDataResponse> GetCatalogkDataAsync(string BookId) {
            Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest inValue = new Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequest();
            inValue.Body = new Kingsun.IBS.BLL.MetadataService.GetCatalogkDataRequestBody();
            inValue.Body.BookId = BookId;
            return ((Kingsun.IBS.BLL.MetadataService.ServiceSoap)(this)).GetCatalogkDataAsync(inValue);
        }
    }
}
