SELECT [CityId]
      ,[ProjectTable]
      ,[BuildingTable]
      ,[HouseTable]
      ,[CaseTable]
      ,[QueryInfoTable]
      ,[ReportTable]
      ,[PrintTable]
      ,[HistoryTable]
      ,[QueryTaxTable]
      ,[CaseBusinessTable]
      ,[CaseLandTable]
      ,[QueryAdjustTable]
      ,[QueryTaxSOATable]
      ,[QueryFlowTable]
      ,[CASHistoryTable]
      ,[MessageTable]
      ,[QueryCheckTable]
      ,[ReportCheckTable]
      ,[SurveyTable]
      ,[SurveyBusinessTable]
      ,[SurveyFactoryTable]
      ,[SurveyLandTable]
      ,[SurveyOfficeTable]
      ,[SurveyOtherTable]
      ,[QueryFilesTable]
      ,[SurveyTextTable]
      ,[SubHousePriceTable]
      ,[QProjectTable]
      ,[ReportEntrustTable]
      ,[SurveyCaseTable]
      ,[SearchHistoryTable]
      ,[QueryYPDat]
      ,[QueryYPCheckTable]
  FROM [dbo].[SYS_City_Table]
  WHERE 1=1