//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSWF.Web.Admin.AreaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AreaService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tableKey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetMetadataResponse GetMetadata(KSWF.Web.Admin.AreaService.GetMetadataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetMetadataResponse> GetMetadataAsync(KSWF.Web.Admin.AreaService.GetMetadataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 districtID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetSchoolDataResponse GetSchoolData(KSWF.Web.Admin.AreaService.GetSchoolDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolDataResponse> GetSchoolDataAsync(KSWF.Web.Admin.AreaService.GetSchoolDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSchoolInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolInfo", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetSchoolInfoResponse GetSchoolInfo(KSWF.Web.Admin.AreaService.GetSchoolInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolInfoResponse> GetSchoolInfoAsync(KSWF.Web.Admin.AreaService.GetSchoolInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAreaDataResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetAreaDataResponse GetAreaData(KSWF.Web.Admin.AreaService.GetAreaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaDataResponse> GetAreaDataAsync(KSWF.Web.Admin.AreaService.GetAreaDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAreaInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaInfo", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetAreaInfoResponse GetAreaInfo(KSWF.Web.Admin.AreaService.GetAreaInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaInfoResponse> GetAreaInfoAsync(KSWF.Web.Admin.AreaService.GetAreaInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Stage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetBookDataResponse GetBookData(KSWF.Web.Admin.AreaService.GetBookDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetBookDataResponse> GetBookDataAsync(KSWF.Web.Admin.AreaService.GetBookDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 BookId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        KSWF.Web.Admin.AreaService.GetCatalogkDataResponse GetCatalogkData(KSWF.Web.Admin.AreaService.GetCatalogkDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetCatalogkDataResponse> GetCatalogkDataAsync(KSWF.Web.Admin.AreaService.GetCatalogkDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadata", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetMetadataRequestBody Body;
        
        public GetMetadataRequest() {
        }
        
        public GetMetadataRequest(KSWF.Web.Admin.AreaService.GetMetadataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMetadataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableKey;
        
        public GetMetadataRequestBody() {
        }
        
        public GetMetadataRequestBody(string tableKey) {
            this.tableKey = tableKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadataResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetMetadataResponseBody Body;
        
        public GetMetadataResponse() {
        }
        
        public GetMetadataResponse(KSWF.Web.Admin.AreaService.GetMetadataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMetadataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMetadataResult;
        
        public GetMetadataResponseBody() {
        }
        
        public GetMetadataResponseBody(string GetMetadataResult) {
            this.GetMetadataResult = GetMetadataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolData", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetSchoolDataRequestBody Body;
        
        public GetSchoolDataRequest() {
        }
        
        public GetSchoolDataRequest(KSWF.Web.Admin.AreaService.GetSchoolDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string districtID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string townsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string schoolName;
        
        public GetSchoolDataRequestBody() {
        }
        
        public GetSchoolDataRequestBody(string districtID, string townsID, string schoolName) {
            this.districtID = districtID;
            this.townsID = townsID;
            this.schoolName = schoolName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetSchoolDataResponseBody Body;
        
        public GetSchoolDataResponse() {
        }
        
        public GetSchoolDataResponse(KSWF.Web.Admin.AreaService.GetSchoolDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchoolDataResult;
        
        public GetSchoolDataResponseBody() {
        }
        
        public GetSchoolDataResponseBody(string GetSchoolDataResult) {
            this.GetSchoolDataResult = GetSchoolDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolInfo", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetSchoolInfoRequestBody Body;
        
        public GetSchoolInfoRequest() {
        }
        
        public GetSchoolInfoRequest(KSWF.Web.Admin.AreaService.GetSchoolInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int schoolID;
        
        public GetSchoolInfoRequestBody() {
        }
        
        public GetSchoolInfoRequestBody(int schoolID) {
            this.schoolID = schoolID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetSchoolInfoResponseBody Body;
        
        public GetSchoolInfoResponse() {
        }
        
        public GetSchoolInfoResponse(KSWF.Web.Admin.AreaService.GetSchoolInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchoolInfoResult;
        
        public GetSchoolInfoResponseBody() {
        }
        
        public GetSchoolInfoResponseBody(string GetSchoolInfoResult) {
            this.GetSchoolInfoResult = GetSchoolInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaData", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetAreaDataRequestBody Body;
        
        public GetAreaDataRequest() {
        }
        
        public GetAreaDataRequest(KSWF.Web.Admin.AreaService.GetAreaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int parentID;
        
        public GetAreaDataRequestBody() {
        }
        
        public GetAreaDataRequestBody(int parentID) {
            this.parentID = parentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetAreaDataResponseBody Body;
        
        public GetAreaDataResponse() {
        }
        
        public GetAreaDataResponse(KSWF.Web.Admin.AreaService.GetAreaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAreaDataResult;
        
        public GetAreaDataResponseBody() {
        }
        
        public GetAreaDataResponseBody(string GetAreaDataResult) {
            this.GetAreaDataResult = GetAreaDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaInfo", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetAreaInfoRequestBody Body;
        
        public GetAreaInfoRequest() {
        }
        
        public GetAreaInfoRequest(KSWF.Web.Admin.AreaService.GetAreaInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AreaID;
        
        public GetAreaInfoRequestBody() {
        }
        
        public GetAreaInfoRequestBody(int AreaID) {
            this.AreaID = AreaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAreaInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAreaInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetAreaInfoResponseBody Body;
        
        public GetAreaInfoResponse() {
        }
        
        public GetAreaInfoResponse(KSWF.Web.Admin.AreaService.GetAreaInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAreaInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAreaInfoResult;
        
        public GetAreaInfoResponseBody() {
        }
        
        public GetAreaInfoResponseBody(string GetAreaInfoResult) {
            this.GetAreaInfoResult = GetAreaInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookData", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetBookDataRequestBody Body;
        
        public GetBookDataRequest() {
        }
        
        public GetBookDataRequest(KSWF.Web.Admin.AreaService.GetBookDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Stage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Grade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Edition;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Booklet;
        
        public GetBookDataRequestBody() {
        }
        
        public GetBookDataRequestBody(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            this.Stage = Stage;
            this.Grade = Grade;
            this.Subject = Subject;
            this.Edition = Edition;
            this.Booklet = Booklet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetBookDataResponseBody Body;
        
        public GetBookDataResponse() {
        }
        
        public GetBookDataResponse(KSWF.Web.Admin.AreaService.GetBookDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookDataResult;
        
        public GetBookDataResponseBody() {
        }
        
        public GetBookDataResponseBody(string GetBookDataResult) {
            this.GetBookDataResult = GetBookDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogkDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogkData", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetCatalogkDataRequestBody Body;
        
        public GetCatalogkDataRequest() {
        }
        
        public GetCatalogkDataRequest(KSWF.Web.Admin.AreaService.GetCatalogkDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogkDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookId;
        
        public GetCatalogkDataRequestBody() {
        }
        
        public GetCatalogkDataRequestBody(string BookId) {
            this.BookId = BookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogkDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogkDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public KSWF.Web.Admin.AreaService.GetCatalogkDataResponseBody Body;
        
        public GetCatalogkDataResponse() {
        }
        
        public GetCatalogkDataResponse(KSWF.Web.Admin.AreaService.GetCatalogkDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogkDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCatalogkDataResult;
        
        public GetCatalogkDataResponseBody() {
        }
        
        public GetCatalogkDataResponseBody(string GetCatalogkDataResult) {
            this.GetCatalogkDataResult = GetCatalogkDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : KSWF.Web.Admin.AreaService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<KSWF.Web.Admin.AreaService.ServiceSoap>, KSWF.Web.Admin.AreaService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetMetadataResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetMetadata(KSWF.Web.Admin.AreaService.GetMetadataRequest request) {
            return base.Channel.GetMetadata(request);
        }
        
        public string GetMetadata(string tableKey) {
            KSWF.Web.Admin.AreaService.GetMetadataRequest inValue = new KSWF.Web.Admin.AreaService.GetMetadataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetMetadataRequestBody();
            inValue.Body.tableKey = tableKey;
            KSWF.Web.Admin.AreaService.GetMetadataResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetMetadata(inValue);
            return retVal.Body.GetMetadataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetMetadataResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetMetadataAsync(KSWF.Web.Admin.AreaService.GetMetadataRequest request) {
            return base.Channel.GetMetadataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetMetadataResponse> GetMetadataAsync(string tableKey) {
            KSWF.Web.Admin.AreaService.GetMetadataRequest inValue = new KSWF.Web.Admin.AreaService.GetMetadataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetMetadataRequestBody();
            inValue.Body.tableKey = tableKey;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetMetadataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetSchoolDataResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetSchoolData(KSWF.Web.Admin.AreaService.GetSchoolDataRequest request) {
            return base.Channel.GetSchoolData(request);
        }
        
        public string GetSchoolData(string districtID, string townsID, string schoolName) {
            KSWF.Web.Admin.AreaService.GetSchoolDataRequest inValue = new KSWF.Web.Admin.AreaService.GetSchoolDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetSchoolDataRequestBody();
            inValue.Body.districtID = districtID;
            inValue.Body.townsID = townsID;
            inValue.Body.schoolName = schoolName;
            KSWF.Web.Admin.AreaService.GetSchoolDataResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetSchoolData(inValue);
            return retVal.Body.GetSchoolDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolDataResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetSchoolDataAsync(KSWF.Web.Admin.AreaService.GetSchoolDataRequest request) {
            return base.Channel.GetSchoolDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolDataResponse> GetSchoolDataAsync(string districtID, string townsID, string schoolName) {
            KSWF.Web.Admin.AreaService.GetSchoolDataRequest inValue = new KSWF.Web.Admin.AreaService.GetSchoolDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetSchoolDataRequestBody();
            inValue.Body.districtID = districtID;
            inValue.Body.townsID = townsID;
            inValue.Body.schoolName = schoolName;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetSchoolDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetSchoolInfoResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetSchoolInfo(KSWF.Web.Admin.AreaService.GetSchoolInfoRequest request) {
            return base.Channel.GetSchoolInfo(request);
        }
        
        public string GetSchoolInfo(int schoolID) {
            KSWF.Web.Admin.AreaService.GetSchoolInfoRequest inValue = new KSWF.Web.Admin.AreaService.GetSchoolInfoRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetSchoolInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            KSWF.Web.Admin.AreaService.GetSchoolInfoResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetSchoolInfo(inValue);
            return retVal.Body.GetSchoolInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolInfoResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetSchoolInfoAsync(KSWF.Web.Admin.AreaService.GetSchoolInfoRequest request) {
            return base.Channel.GetSchoolInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetSchoolInfoResponse> GetSchoolInfoAsync(int schoolID) {
            KSWF.Web.Admin.AreaService.GetSchoolInfoRequest inValue = new KSWF.Web.Admin.AreaService.GetSchoolInfoRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetSchoolInfoRequestBody();
            inValue.Body.schoolID = schoolID;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetSchoolInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetAreaDataResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetAreaData(KSWF.Web.Admin.AreaService.GetAreaDataRequest request) {
            return base.Channel.GetAreaData(request);
        }
        
        public string GetAreaData(int parentID) {
            KSWF.Web.Admin.AreaService.GetAreaDataRequest inValue = new KSWF.Web.Admin.AreaService.GetAreaDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetAreaDataRequestBody();
            inValue.Body.parentID = parentID;
            KSWF.Web.Admin.AreaService.GetAreaDataResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetAreaData(inValue);
            return retVal.Body.GetAreaDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaDataResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetAreaDataAsync(KSWF.Web.Admin.AreaService.GetAreaDataRequest request) {
            return base.Channel.GetAreaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaDataResponse> GetAreaDataAsync(int parentID) {
            KSWF.Web.Admin.AreaService.GetAreaDataRequest inValue = new KSWF.Web.Admin.AreaService.GetAreaDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetAreaDataRequestBody();
            inValue.Body.parentID = parentID;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetAreaDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetAreaInfoResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetAreaInfo(KSWF.Web.Admin.AreaService.GetAreaInfoRequest request) {
            return base.Channel.GetAreaInfo(request);
        }
        
        public string GetAreaInfo(int AreaID) {
            KSWF.Web.Admin.AreaService.GetAreaInfoRequest inValue = new KSWF.Web.Admin.AreaService.GetAreaInfoRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetAreaInfoRequestBody();
            inValue.Body.AreaID = AreaID;
            KSWF.Web.Admin.AreaService.GetAreaInfoResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetAreaInfo(inValue);
            return retVal.Body.GetAreaInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaInfoResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetAreaInfoAsync(KSWF.Web.Admin.AreaService.GetAreaInfoRequest request) {
            return base.Channel.GetAreaInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetAreaInfoResponse> GetAreaInfoAsync(int AreaID) {
            KSWF.Web.Admin.AreaService.GetAreaInfoRequest inValue = new KSWF.Web.Admin.AreaService.GetAreaInfoRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetAreaInfoRequestBody();
            inValue.Body.AreaID = AreaID;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetAreaInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetBookDataResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetBookData(KSWF.Web.Admin.AreaService.GetBookDataRequest request) {
            return base.Channel.GetBookData(request);
        }
        
        public string GetBookData(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            KSWF.Web.Admin.AreaService.GetBookDataRequest inValue = new KSWF.Web.Admin.AreaService.GetBookDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetBookDataRequestBody();
            inValue.Body.Stage = Stage;
            inValue.Body.Grade = Grade;
            inValue.Body.Subject = Subject;
            inValue.Body.Edition = Edition;
            inValue.Body.Booklet = Booklet;
            KSWF.Web.Admin.AreaService.GetBookDataResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetBookData(inValue);
            return retVal.Body.GetBookDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetBookDataResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetBookDataAsync(KSWF.Web.Admin.AreaService.GetBookDataRequest request) {
            return base.Channel.GetBookDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetBookDataResponse> GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            KSWF.Web.Admin.AreaService.GetBookDataRequest inValue = new KSWF.Web.Admin.AreaService.GetBookDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetBookDataRequestBody();
            inValue.Body.Stage = Stage;
            inValue.Body.Grade = Grade;
            inValue.Body.Subject = Subject;
            inValue.Body.Edition = Edition;
            inValue.Body.Booklet = Booklet;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetBookDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KSWF.Web.Admin.AreaService.GetCatalogkDataResponse KSWF.Web.Admin.AreaService.ServiceSoap.GetCatalogkData(KSWF.Web.Admin.AreaService.GetCatalogkDataRequest request) {
            return base.Channel.GetCatalogkData(request);
        }
        
        public string GetCatalogkData(string BookId) {
            KSWF.Web.Admin.AreaService.GetCatalogkDataRequest inValue = new KSWF.Web.Admin.AreaService.GetCatalogkDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetCatalogkDataRequestBody();
            inValue.Body.BookId = BookId;
            KSWF.Web.Admin.AreaService.GetCatalogkDataResponse retVal = ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetCatalogkData(inValue);
            return retVal.Body.GetCatalogkDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetCatalogkDataResponse> KSWF.Web.Admin.AreaService.ServiceSoap.GetCatalogkDataAsync(KSWF.Web.Admin.AreaService.GetCatalogkDataRequest request) {
            return base.Channel.GetCatalogkDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<KSWF.Web.Admin.AreaService.GetCatalogkDataResponse> GetCatalogkDataAsync(string BookId) {
            KSWF.Web.Admin.AreaService.GetCatalogkDataRequest inValue = new KSWF.Web.Admin.AreaService.GetCatalogkDataRequest();
            inValue.Body = new KSWF.Web.Admin.AreaService.GetCatalogkDataRequestBody();
            inValue.Body.BookId = BookId;
            return ((KSWF.Web.Admin.AreaService.ServiceSoap)(this)).GetCatalogkDataAsync(inValue);
        }
    }
}
